# Generated by Django 6.0.3 on 2026-03-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuroTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=50, unique=True, verbose_name='ID da Reserva')),
                ('guest', models.CharField(max_length=255, verbose_name='Hóspede')),
                ('vehicle', models.CharField(max_length=255, verbose_name='Veículo')),
                ('vehicle_name', models.CharField(max_length=255, verbose_name='Nome do Veículo')),
                ('vehicle_id', models.CharField(max_length=50, verbose_name='ID do Veículo')),
                ('vin', models.CharField(max_length=50, verbose_name='VIN')),
                ('start_date', models.DateTimeField(verbose_name='Início da Viagem')),
                ('end_date', models.DateTimeField(verbose_name='Fim da Viagem')),
                ('pickup_location', models.TextField(verbose_name='Local de Retirada')),
                ('return_location', models.TextField(verbose_name='Local de Devolução')),
                ('trip_status', models.CharField(max_length=100, verbose_name='Status da Viagem')),
                ('check_in_odometer', models.IntegerField(blank=True, null=True, verbose_name='Odômetro Check-in')),
                ('check_out_odometer', models.IntegerField(blank=True, null=True, verbose_name='Odômetro Check-out')),
                ('distance_traveled', models.IntegerField(blank=True, null=True, verbose_name='Distância Percorrida')),
                ('trip_days', models.IntegerField(verbose_name='Dias de Viagem')),
                ('trip_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da Viagem')),
                ('boost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Boost')),
                ('discount_3_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto 3 dias')),
                ('discount_1_week', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto 1 semana')),
                ('discount_2_week', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto 2 semanas')),
                ('discount_3_week', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto 3 semanas')),
                ('discount_1_month', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto 1 mês')),
                ('discount_2_month', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto 2 meses')),
                ('discount_3_month', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto 3 meses')),
                ('discount_non_refundable', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto Não Reembolsável')),
                ('discount_early_bird', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto Early Bird')),
                ('host_promotional_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Crédito Promocional Host')),
                ('delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Entrega')),
                ('excess_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Distância Excedente')),
                ('extras', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Extras')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Cancelamento')),
                ('additional_usage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Uso Adicional')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Atraso')),
                ('improper_return_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Devolução Inadequada')),
                ('airport_operations_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Operação Aeroportuária')),
                ('airport_parking_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Crédito de Estacionamento Aeroporto')),
                ('tolls_and_tickets', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pedágios e Multas de Trânsito')),
                ('on_trip_ev_charging', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Carregamento EV em Viagem')),
                ('post_trip_ev_charging', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Carregamento EV pós Viagem')),
                ('smoking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Fumo')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Limpeza')),
                ('fines_paid_to_host', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multas pagas ao Host')),
                ('gas_reimbursement', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reembolso de Combustível')),
                ('gas_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Combustível')),
                ('other_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Outras Taxas')),
                ('sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Imposto sobre Vendas')),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganhos Totais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-start_date'],
            },
        ),
    ]
