# Generated by Django 6.0.3 on 2026-03-27 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Investidor')),
                ('status', models.CharField(default='Active', max_length=50, verbose_name='Status')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Investido')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investidor',
                'verbose_name_plural': 'Investidores',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=50, unique=True, verbose_name='VIN')),
                ('plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('year_make_model', models.CharField(max_length=255, verbose_name='Ano/Marca/Modelo')),
                ('status', models.CharField(default='Active', max_length=50, verbose_name='Status')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_vehicles', to='dashboard.investor', verbose_name='Investidor')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
