# Generated by Django 6.0.3 on 2026-03-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_investor_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=20, unique=True, verbose_name='Chave do Período (AAAA-MM)')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='turotrip',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='turotrip',
            name='vehicle_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='dashboard.vehicle', verbose_name='Veículo Relacionado'),
        ),
        migrations.AddField(
            model_name='turotrip',
            name='vehicle_str',
            field=models.CharField(default='', max_length=255, verbose_name='Veículo (Texto)'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Investimento')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Porcentagem de Propriedade (%)')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Investido')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('duration_days', models.IntegerField(blank=True, null=True, verbose_name='Duração (Dias)')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='dashboard.investor', verbose_name='Investidor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='dashboard.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Despesa')),
                ('expense_type', models.CharField(choices=[('Maintenance', 'Manutenção'), ('Repair', 'Reparo'), ('Cleaning', 'Limpeza'), ('Gas', 'Combustível'), ('Insurance', 'Seguro'), ('Other', 'Outros')], max_length=50, verbose_name='Tipo de Despesa')),
                ('date', models.DateField(verbose_name='Data')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(default='Approved', max_length=50, verbose_name='Status')),
                ('payment_status', models.CharField(default='Paid', max_length=50, verbose_name='Status do Pagamento')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='dashboard.vehicle', verbose_name='Veículo')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='dashboard.period', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.AddField(
            model_name='turotrip',
            name='period_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='dashboard.period', verbose_name='Período Relacionado'),
        ),
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolls', to='dashboard.period', verbose_name='Período')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolls', to='dashboard.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Pedágio',
                'verbose_name_plural': 'Pedágios',
            },
        ),
    ]
