# Generated by Django 6.0.3 on 2026-03-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_period_remove_turotrip_vehicle_turotrip_vehicle_obj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='total_invested',
        ),
    ]
