# Generated by Django 6.0.3 on 2026-03-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_investor_total_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='turotrip',
            name='plate_extracted',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa Extraída'),
        ),
    ]
